# Generated by Django 5.0.6 on 2024-08-04 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcell', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiter',
            name='has_paid',
            field=models.BooleanField(default=False),
        ),
    ]
